global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""
  name: cnosdb

kubeVersion: ""
nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""
clusterDomain: cluster.local
commonAnnotations: {}
commonLabels: {}
extraDeploy: []

clusterName: cluster_xxx
image:
  registry: docker.io
  repository: knightxun/cnosdb
  tag: v2.3.0-k8s
  digest: ""
  pullPolicy: IfNotPresent
  pullSecrets: []
  debug: false

config:
  cpu: 4
  memory: 4
  storageSize: 10Gi
  tskv:
    replicas: 3
    max_summary_size: 134217728
    max_level: 4 
    base_file_size: 16777216
    compact_trigger: 4
    existingConfigmap: ""
    max_compact_size: "2G"
    cache:
      max_buffer_size: "2G"
    port:
      http_listen_port: 21001
      grpc_listen_port: 21002
      tcp_listen_port: 21003
      flight_rpc_listen_port: 21004
    resources:
      limits: {}
      requests: {}
  meta:
    replicas: 1
    port: 
      meta_port: 21000
    resources:
      limits: {}
      requests: {}

networkPolicy:
  enabled: false
  allowExternal: true
  explicitNamespacesSelector: {}