apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: cnosdb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      app: cnosdb
  template:
    metadata:
      labels:
        app: cnosdb
    spec:
      containers:
      - name: cnosdb
        image: cnosdb/cnosdb:latest
        resources:
          requests:
            cpu: {{ .Values.config.resources.requests.cpu }}
            memory: {{ .Values.config.resources.requests.cpu }}
          limits:
            cpu: {{ .Values.config.resources.limits.cpu }}
            memory: {{ .Values.config.resources.limits.cpu }}
        env:
        - name: cpu
          value: "{{ .Values.config.cpu }}"
        - name: memory
          value: "{{ .Values.config.memory }}"
        ports:
        - name: cnosdb
          containerPort: {{ .Values.config.service.ports.cnosdb }}
          protocol: TCP
        volumeMounts:
          - name: cnosdbvolume
            mountPath: /cnosdb
          - name: cnosdb
            mountPath: /etc/config/
      volumes:
      - name: cnosdbvolume
        hostPath:
          path: /opt/data
      - name: cnosdb
        configMap:
          name: cnosdb