#cloud-config
# vim:syntax=yaml
debug: True
ssh_pwauth: False
disable_root: False
runcmd:
- yum install numactl -y 
- yum install docker-ce -y 
- systemctl start docker
- docker run -itd  --env cpu=2 --env memory=4 -p 31007:31007 cnosdb/cnosdb